version: '3.1'

services:
  
  adminer:
    image: adminer
    ports:
        - 8080:8080


  db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: Shop
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
        - 3306:3306

  authentication:
    image: authen
    ports:
        - 5000:5000
    volumes:
      - migrations-data:/usr/local/app/migrations
    depends_on:
        - db
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=3306
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=3

volumes:
  mysql-data:
  migrations-data: