version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8083:8080
      - 7077:7077
    cpus: 0.5
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - shop  
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8084:8081
    cpus: 0.5
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - shop  
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8085:8081
    cpus: 0.5
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - shop  
  spark-history-server:
      image: bde2020/spark-history-server:3.3.0-hadoop3.3
      container_name: spark-history-server
      depends_on:
        - spark-master
      ports:
        - 18081:18081
      cpus: 0.2
      volumes:
        - /tmp/spark-events-local:/tmp/spark-events
      networks:
        - shop  


  sparkapp:
    image: sparkapp:latest
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    cpus: 0.4
    networks:
      - shop
      - stats    
  
networks:
  shop:
    external: true
    name: shop-network
  stats:
    external: true
    name: shop-stats
